name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
